name: Black - Format code
on: [push, pull_request]

jobs:
  black:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installing black formatter
        run: pip install black
      - name: Check using black
        run: black . -q
      - name: Annotate diff changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
